//** Exception Handling */


// throw new Error('Error Message');

try {
    console.log("Start try block");
    lalal;
    console.log("End try block");
} catch (err) {
    console.log("Error Message", err);
}

